
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StarStand
{

using System;
    using System.Collections.Generic;
    
public partial class Carros
{

    public int IdCarro { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string Matricula { get; set; }

    public string Combustivel { get; set; }

}

}
