//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarStand
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoServicos : Servicos
    {
        public int IdHistoricoServicos { get; set; }
        public string DataSaida { get; set; }
        public string CarroOficinaIdCarroOficina { get; set; }
    
        public virtual CarroOficina CarroOficina { get; set; }
    }
}
