
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StarStand
{

using System;
    using System.Collections.Generic;
    
public partial class Pecas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pecas()
    {

        this.Servicos = new HashSet<Servicos>();

    }


    public int IdPecas { get; set; }

    public double Valor { get; set; }

    public int Stock { get; set; }

    public string ServicoIdServicos { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Servicos> Servicos { get; set; }

}

}
