

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StarStand
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class starBDContainer : DbContext
{
    public starBDContainer()
        : base("name=starBDContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Utilizadores> UtilizadoresSet { get; set; }

    public virtual DbSet<Carros> CarrosSet { get; set; }

    public virtual DbSet<Venda> VendaSet { get; set; }

    public virtual DbSet<Pecas> PecasSet { get; set; }

    public virtual DbSet<Servicos> ServicosSet { get; set; }

    public virtual DbSet<Aluguer> AluguerSet { get; set; }

}

}

