//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarStand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizadores()
        {
            this.Venda = new HashSet<Venda>();
            this.Aluguer = new HashSet<Aluguer>();
            this.CarroOficina = new HashSet<CarroOficina>();
        }
    
        public int IdUtilizador { get; set; }
        public string Nome { get; set; }
        public int NIF { get; set; }
        public string Morada { get; set; }
        public string Telemovel { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venda> Venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aluguer> Aluguer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarroOficina> CarroOficina { get; set; }
    }
}
