//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarStand
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int IdVenda { get; set; }
        public string Valor { get; set; }
        public string Estado { get; set; }
        public string Data { get; set; }
        public int UtilizadoresIdUtilizador { get; set; }
    
        public virtual Utilizadores Utilizadores { get; set; }
        public virtual CarroVenda CarroVenda { get; set; }
    }
}
